### PR TITLE
Fix invalid phone number error message

### LINKED ISSUE #247: Error message for invalid phone number has a typo

### PR DESCRIPTION
**Pull request by Dinoman44**
Fixes #247

### CODE REVIEW

File: src/main/java/seedu/address/model/person/ClientStatus.java [hunk 1]
```diff
@@ -11,7 +11,7 @@ public class ClientStatus {
 
     public static final String MESSAGE_CONSTRAINTS =
             "Client status must be either “active”, “unresponsive”,"
-            + " “potential” or “old” (case insensitive).";
+            + " “potential”, “old” or “blacklisted” (case insensitive).";
```
Comment (Dinoman44) [inline src/main/java/seedu/address/model/person/ClientStatus.java:14]: Ignore this change, its the same as #246 for some reason my branching has gone to shit

**Review by JunLongling — APPROVED** [review]
LGTM
